// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package randomgenerator.actions;

import java.util.Random;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetRandomNumber extends CustomJavaAction<java.lang.Long>
{
	private java.lang.Long MaximumRange;

	public GetRandomNumber(IContext context, java.lang.Long MaximumRange)
	{
		super(context);
		this.MaximumRange = MaximumRange;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		// BEGIN USER CODE
		
        Random random = new Random(); 
        
        int RandomNumber = random.nextInt(MaximumRange.intValue());        
        
        return Long.valueOf(RandomNumber);      
        
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetRandomNumber";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
